config/routes.rb
Rails.application.routes.draw do
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  @contacts = Contact.all
  end

  def new
  end

  def create
  @contact = Contact.new(contact_params)
  @contact.save
  redirect_to @contact
  end

  def show
  @contact = Contact.find(params[:id])
  end

  def edit
  @contact = Contact.find(params[:id])
  end

  def update
  @contact = Contact.find(params[:id])
   if @contact.update(contact_params)
    redirect_to @contact
  else
    render 'edit'
  end
  end

  def destroy
  @contact= Contact.find(params[:id])
  @contact.destroy
  redirect_to contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email_id, :mobile_no, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>Contacts Editing</h1>
 
<%= form_for :contact, url: contact_path(@contact), method: :patch do |c| %>
  <% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contact.errors.count, "error") %>Found some errors!! </h2>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<p>
	<%= c.label :first_name %>
	<%= c.text_field :first_name %>
</p>
<p>
	<%= c.label :last_name %>
	<%= c.text_field :last_name %>
</p>
<p>
	<%= c.label :email_id %>
	<%= c.text_field :email_id %>
</p>
<p>
	<%= c.label :mobile_no %>
	<%= c.text_field :mobile_no %>
</p>
<p>
	<%= c.label :address %>
	<%= c.text_area :address %>
</p>
<p>
	<%= c.submit %>
</p>
<% end %>
 
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h2> Available contacts </h2>
<%= link_to 'New Contact', new_contact_path %>
<table border="2">
<tr>
 <th>FirstName</th>
 <th>LastName</th>
 <th>Email_id</th>
 <th>Mobile_no</th>
 <th>Address</th>
</tr>
 
<% @contacts.each do |contact| %>
 <tr>
  <td><%= contact.first_name %></td>
  <td><%= contact.last_name %></td>
  <td><%= contact.email_id %></td>
  <td><%= contact.mobile_no %></td>
  <td><%= contact.address %></td>
  <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
  <td><%= link_to 'show', contact_path(contact) %></td>
<td><%= link_to 'Destroy', contact_path(contact),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
 </tr>
<%end%>
</table>

app/views/contacts/new.html.erb
<h1> New Contact </h1>
<%= form_for :contact, url: contacts_path do |c| %>
<p>
	<%= c.label :first_name %><br>
	<%= c.text_field :first_name %>
</p>
<p>
	<%= c.label :last_name %><br>
	<%= c.text_field :last_name %>
</p>
<p>
	<%= c.label :email_id %><br>
	<%= c.text_field :email_id %>
</p>
<p>
	<%= c.label :mobile_no %><br>
	<%= c.text_field :mobile_no %>
</p>
<p>
	<%= c.label :address %><br>
	<%= c.text_area :address %>
</p>
<p>
	<%= c.submit %>
</p>
<% end %>
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
	<strong> First_name: </strong>
	<%= @contact.first_name %>
</p>
<p>
	<strong> Last_name: </strong>
	<%= @contact.last_name %>
</p>
<p>
	<strong> Email_id: </strong>
	<%= @contact.email_id %>
</p>
<p>
	<strong> Mobile_no: </strong>
	<%= @contact.mobile_no %>
</p>
<p>
	<strong> Address: </strong>
	<%= @contact.address %>
</p>
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>